### PR TITLE
Patch for noexecstack

### PR DESCRIPTION
**Pull request by RajUmadas**
Simon,

I have been playing around with the RPI for a bit and noticed that when i updated to the new raspian, all my bin had executable stacks. I tracked it down to the lib with the modified memcpy and memset. I believe these edits i made will fix the stack perms. If you agree, i would love if you could merge this back into the master. 

Thanks,
Raj

### CODE REVIEW

**Comment by RajUmadas** [comment]
Also, its cool to note i did this on my pi. :)

**Comment by RajUmadas** [comment]
For more details...
http://www.gentoo.org/proj/en/hardened/gnu-stack.xml

**Comment by simonjhall** [comment]
Excellent stuff. Many thanks for the contribution.
A super minor thing however - renaming the files does not appear to be necessary: the same tool is being invoked via Make (as) and testing locally the section still gets correctly emitted by the assembler. Or is this just a convention (eg I don't name my files .hello!). Thoughts?

**Comment by RajUmadas** [comment]
Thanks for the reply. I am just happy to contribute. The filename was used due to convention. Id imagine, if the builds use your makefile, things will work well. However, if someone just pull the asm files and tries to incorporate that into their project, they might forget to invoke the preprocessor. For the rpi project, it shouldn't matter. It would probably be best to have some of the other more experienced rpi dev comment on it, but im sure you can make the best decisions on that. 

Looking forward to seeing this in raspian. NoExec stacks are awesome. 

Raj

**Comment by simonjhall** [comment]
Good enough for me!

**Comment by RajUmadas** [comment]
Thanks.

**Pull request merged**
